# Form implementation generated from reading ui file 'QHistory.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from PyQt6.QtWidgets import QWidget, QHeaderView, QSizePolicy

from Models.ProductModel import ProductModel
from utilities import make_window_center


class _Ui_History(object):
    def __init__(self):
        self.tableView: QtWidgets.QTableView | None = None

    def setupUi(self, History):
        History.setObjectName("search_result")
        History.resize(800, 600)
        self.container = QtWidgets.QHBoxLayout()
        self.container.setContentsMargins(0, 0, 0, 0)
        History.setLayout(self.container)
        self.model = ProductModel()
        self.model.select()

        self.tableView = QtWidgets.QTableView(History)
        self.tableView.setModel(self.model)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.tableView.setContentsMargins(0, 0, 0, 0)
        self.tableView.setSortingEnabled(True)
        self.tableView.resizeColumnsToContents()
        self.tableView.setSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.MinimumExpanding)
        self.container.addWidget(self.tableView)
        self.retranslateUi(History)
        QtCore.QMetaObject.connectSlotsByName(History)
        make_window_center(History)

    def retranslateUi(self, History):
        _translate = QtCore.QCoreApplication.translate
        History.setWindowTitle(_translate("Search Result", "Search Result"))


class QHistory(QWidget, _Ui_History):
    def __init__(self, *args, obj=None, **kwargs):
        super(QHistory, self).__init__()
        self.setupUi(self)
