# Form implementation generated from reading ui file 'QSearchResult.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from PyQt6.QtWidgets import QWidget, QHeaderView, QSizePolicy

from utilities import make_window_center


class _Ui_SearchResult(object):
    def __init__(self):
        self.tableView: QtWidgets.QTableView | None = None

    def setupUi(self, SearchResult):
        SearchResult.setObjectName("search_result")
        SearchResult.resize(800, 600)
        self.container = QtWidgets.QHBoxLayout()
        self.container.setContentsMargins(0, 0, 0, 0)
        SearchResult.setLayout(self.container)
        self.tableView = QtWidgets.QTableView(SearchResult)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.tableView.setContentsMargins(0, 0, 0, 0)
        self.tableView.setSortingEnabled(True)
        self.tableView.resizeColumnsToContents()
        self.tableView.setSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.MinimumExpanding)
        self.container.addWidget(self.tableView)
        self.retranslateUi(SearchResult)
        QtCore.QMetaObject.connectSlotsByName(SearchResult)
        make_window_center(SearchResult)

    def retranslateUi(self, SearchResult):
        _translate = QtCore.QCoreApplication.translate
        SearchResult.setWindowTitle(_translate("Search Result", "Search Result"))


class QSearchResult(QWidget, _Ui_SearchResult):
    def __init__(self, *args, obj=None, **kwargs):
        super(QSearchResult, self).__init__()
        self.setupUi(self)

        if 'model' in kwargs:
            self.tableView.setModel(kwargs['model'])

    def setModel(self, model):
        self.tableView.setModel(model)
